# 1.3.1

# (Optional) Default exec command when open files.
# If not set, will default to $EDITOR
default = "nvim"

# (Optional) Whether to use the full width of terminal.
# If not set, this will be true.
# use_full_width = true

# (Optional) Set the max length of item name to be displayed.
# This works only when use_full_width is set to false.
# If the terminal size is not enough, the length will be changed to fit it.
# If not set, this will be 30.
# item_name_length = 30

# (Optional)
# key (the command you want to use) = [values] (extensions)
# [exec]
# feh = [\"jpg\", \"jpeg\", \"png\", \"gif\", \"svg\"]
# zathura = [\"pdf\"]

# The foreground color of directory, file and symlink.
# Pick one of the following:
#     Black
#     Red
#     Green
#     Yellow
#     Blue
#     Magenta
#     Cyan
#     White
#     LightBlack
#     LightRed
#     LightGreen
#     LightYellow
#     LightBlue
#     LightMagenta
#     LightCyan
#     LightWhite
#     Rgb(u8, u8, u8)
#     AnsiValue(u8)
[color]
dir_fg = "LightCyan"
file_fg = "LightWhite"
symlink_fg = "LightYellow"
