# default exec command when open files
default = "nvim"

# default text editor
# editor = "nvim"

# key(command you want to use) = values(extensions)
[exec]
feh = ["jpg", "jpeg", "png", "gif", "svg"]
zathura = ["pdf"]

# the foreground color of file and directory in the list
# Pick one of the following:
#   AnsiValue(u8)
#   Black
#   Blue
#   Cyan
#   Green
#   LightBlack
#   LightBlue
#   LightCyan
#   LightGreen
#   LightMagenta
#   LightRed
#   LightWhite
#   LightYellow
#   Magenta
#   Red
#   Rgb(u8, u8, u8)
#   White
#   Yellow
# For more detail, read https://docs.rs/termion/1.5.6/termion/color/index.html
[color]
dir_fg = "LightCyan"
file_fg = "LightWhite"
symlink_fg = "LightYellow"
