#0.9.8

# default exec command when open files
default = "nvim"

# Whether to use the full width of terminal.
# If not set, this will be false.
use_full_width = false

# Option: Set the max length of item name to be displayed.
# This works only when use_full_width is set to false.
# If the terminal size is not enough, the length will be changed to fit it.
# If not set, this will be 30.
# item_name_length = 30

# key(the command you want to use) = values(extensions)
# [exec]
# feh = ["jpg", "jpeg", "png", "gif", "svg"]
# zathura = ["pdf"]

# the foreground color of file and directory in the list
# Pick one of the following:
#   AnsiValue(u8)
#   Black
#   Blue
#   Cyan
#   Green
#   LightBlack
#   LightBlue
#   LightCyan
#   LightGreen
#   LightMagenta
#   LightRed
#   LightWhite
#   LightYellow
#   Magenta
#   Red
#   Rgb(u8, u8, u8)
#   White
#   Yellow
# For more detail, read https://docs.rs/termion/1.5.6/termion/color/index.html
[color]
dir_fg = "LightCyan"
file_fg = "LightWhite"
symlink_fg = "LightYellow"
